//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerceptronAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeakListData
    {
        public string FileUniqueId { get; set; }
        public string PeakListMasses { get; set; }
        public string PeakListIntensities { get; set; }
        public Nullable<System.DateTime> JobSubmission { get; set; }
    }
}
