//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerceptronAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultPtmSite
    {
        public string ResultId { get; set; }
        public int Index { get; set; }
        public double Score { get; set; }
        public double ModWeight { get; set; }
        public string ModName { get; set; }
        public string AminoAcid { get; set; }
        public string Site { get; set; }
    }
}
