//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerceptronAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchResult
    {
        public string QueryId { get; set; }
        public string ResultId { get; set; }
        public string Header { get; set; }
        public string Sequence { get; set; }
        public double PstScore { get; set; }
        public double InsilicoScore { get; set; }
        public double PtmScore { get; set; }
        public double Score { get; set; }
        public double MwScore { get; set; }
        public double Mw { get; set; }
        public string FileId { get; set; }
    }
}
