//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerceptronLocalService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PtmVariableModification
    {
        public System.DateTime JobSubmission { get; set; }
        public int ModificationId { get; set; }
        public string QueryId { get; set; }
        public string VariableModifications { get; set; }
    }
}
