//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerceptronLocalService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultsDownloadable
    {
        public string QueryId { get; set; }
        public string ResultId { get; set; }
        public string MassSpectrumImageFilePath { get; set; }
        public string JsonExpThrTableFilePath { get; set; }
        public string CompleteDetailedResultsFilePath { get; set; }
    }
}
