//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerceptronLocalService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchQuery
    {
        public Nullable<System.DateTime> JobSubmission { get; set; }
        public string QueryId { get; set; }
        public string UserId { get; set; }
        public string Progress { get; set; }
        public string CreationTime { get; set; }
    }
}
