'[{"Title":"Default Run","FDRCutOff":"0.0","ProteinDatabase":"Human","FileName":"C:\\fakepath\\HELA_pk13_sw1_66sc_mono.txt","NumberOfOutputs":"100+","MassMode":"M(Neutral)","FilterDb":true,"MwTolerance":500,"PeptideTolerance":15,"PeptideToleranceUnit":"ppm","Autotune":false,"InsilicoFragType":"HCD","HandleIons":"bo,bstar,yo,ystar","DenovoAllow":true,"MinimumPstLength":"3","MaximumPstLength":6,"HopThreshhold":0.1,"Hop_Tolerance_Unit":"Da","PSTTolerance":0.45,"Truncation":false,"TerminalModification":"None,NME,NME_Acetylation,M_Acetylation","PtmAllow":false,"PtmTolerance":0.5,"List_of_Modifications":"","Variable_Modifications":"","MethionineChemicalModification":"None","Fixed_Modification":"","CysteineChemicalModification":"None","MwSweight":"0","PstSweight":"0","InsilicoSweight":"100","VariableModifications":"","FixedModifications":"","EmailId":"farhan.khalid@lums.edu.pk","UserId":"farhan.khalid@lums.edu.pk","FDR_CutOff":"0.0"}]'



% % Will use later
% % weboptions('RequestMethod','POST','ContentType', 'json','Timeout',60,'KeyName','Authorization','KeyValue','abc230')







{"Title":"Default Run","FDRCutOff":"0.0","ProteinDatabase":"Human",...
    "FileName":"C:\\fakepath\\HELA_pk13_sw1_66sc_mono.txt","NumberOfOutputs":"100+","MassMode":...
    "M(Neutral)","FilterDb":true,"MwTolerance":500,"PeptideTolerance":15,"PeptideToleranceUnit":"ppm",...
    "Autotune":false,"InsilicoFragType":"HCD","HandleIons":"bo,bstar,yo,ystar","DenovoAllow":true,...
    "MinimumPstLength":"3","MaximumPstLength":6,"HopThreshhold":0.1,"Hop_Tolerance_Unit":"Da",...
    "PSTTolerance":0.45,"Truncation":false,"TerminalModification":"None,NME,NME_Acetylation,M_Acetylation",...
    "PtmAllow":false,"PtmTolerance":0.5,"List_of_Modifications":"","Variable_Modifications":"",...
    "MethionineChemicalModification":"None","Fixed_Modification":"","CysteineChemicalModification":"None",...
    "MwSweight":"0","PstSweight":"0","InsilicoSweight":"100","VariableModifications":"",...
    "FixedModifications":"",...
    "EmailId":"farhan.khalid@lums.edu.pk","UserId":"farhan.khalid@lums.edu.pk","FDR_CutOff":"0.0"}